### ISSUE TITLE
Profile Pictures

### ISSUE THREAD

**Issue by aeonsablaze** [Hive13/HiveWeb#15]
Feature request: We have been taking pictures of new members for identification purposes, however we don't really have a standard place to keep and organize them. The ability to include a profile picture on a member account would go some distance toward solving this.

**Comment by DrunkPyromaniac** [comment]
@ry13 May be interested to see this progress.

**Comment by DrunkPyromaniac** [comment]
#21 live.  Still working on change/delete.

**Comment by DrunkPyromaniac** [comment]
#22 live also.

**Comment by DrunkPyromaniac** [comment]
#25

**Comment by DrunkPyromaniac** [comment]
#28 live.  This is now done.
