### ISSUE TITLE
Alternate username options during login

### ISSUE THREAD

**Issue by aeonsablaze** [Hive13/HiveWeb#24]
Suggestion: When logging in the username field can accept any of: contact email, paypal email, handle

**Comment by DrunkPyromaniac** [comment]
The problem with the PayPal e-mail field is that it's not unique - two accounts could share the same e-mail address there, and anyone paying not through PayPal is blank or something else.

As to handle, yeah, that's fine, I just need to mark that field unique in the DB.

**Comment by aeonsablaze** [comment]
Fair point. Just handle and email should be fine.

Or, in the interest of overcomplicating thing, could we allow paypal email IF there is only one account using that particular address?

**Comment by DrunkPyromaniac** [comment]
Merged #84.  Added support for handles.  If you think PayPal e-mail is important, open up another ticket and I'll figure out how to handle a non-unique field.
