### ISSUE TITLE
Last Credit Indicator

### ISSUE THREAD

**Issue by aeonsablaze** [Hive13/HiveWeb#318]
Some kind of signal (sound, light, whatever) to indicate when you have just used your last credit. That way you know you need to add more ahead of time rather than finding out the next time you are trying to get a soda.

**Comment by aeonsablaze** [comment]
Idea: signal could also be an email sent from intweb when you are out of credits.

**Comment by DrunkPyromaniac** [comment]
Have it be a setting on your profile to either alert on the machine, send e-mail, both, or none.
