### ISSUE TITLE
trim spaces from form entries

### ISSUE THREAD

**Issue by cjdavis** [Hive13/HiveWeb#358]
https://hive13.slack.com/archives/C04Q9C12U/p1594850711199300

**Comment by cjdavis** [comment]
> I want to complain that intweb doesn't trim login info. My phone auto-inserts a space after my email and intweb does not like that one bit
<sub>[View in Slack](https://hive13.slack.com/archives/C04Q9C12U/p1594850711199300)</sub>

**Comment by cjdavis** [comment]
Does a comment on an issue show up in the slack #intweb channel?

**Comment by pvince** [comment]
This might be obvious, but make sure if // when this is implemented, the code only trims the username, not the password.

Further, the following situations should be checked:

- Make sure the other user management pages (signup, etc...) are also trimming the username.
- Confirm that there are no users in the database with trailing or leading whitespace.

**Comment by kirkmawa** [comment]
This PR should take care of the issue. Simple oversight. I'll batch this one with the other PR today and get the application server synced up

**Comment by kirkmawa** [comment]
Verified no email addresses have whitespace in the database. The following queries return no rows:

```
SELECT * FROM public.members
WHERE email like '% '
```

```
SELECT * FROM public.members
WHERE email like ' %'
```

Merging now.
