### ISSUE TITLE
Gracefully handle unauthorized access

### ISSUE THREAD

**Issue by aeonsablaze** [Hive13/HiveWeb#45]
Currently, going to a page you cannot access displays a large unwieldy page of error output. I would suggest that trying to access a page you are not authorized for should redirect to the intweb home page if you are logged in, or the login page if you are not. On a semi-related note, the login page should probably redirect to the homepage if you are already logged in.

Steps to reproduce the issue:
Log out and go here:
https://intweb.at.hive13.org/admin/members/view
Log on and go here:
https://intweb.at.hive13.org/login

**Comment by DrunkPyromaniac** [comment]
Merged #61.
