### ISSUE TITLE
Sessions are not persistant between sub-domains

### ISSUE THREAD

**Issue by aeonsablaze** [Hive13/HiveWeb#46]
Logged-in sessions are not persistent between sub-domains, i.e. when logged in and working on intweb.at.hive13.org, if you open a link to intweb.hive13.org it will treat you as not logged-in. I'm not sure if this is easily solved on the application side, but we could potentially solve it via apache/nginx by using a url rewrite and just directing any requests for intweb.at.hive13.org to intweb.hive13.org or vice-versa.

**Comment by DrunkPyromaniac** [comment]
It stores the session in cookies.  I suppose we could re-write everything to intweb.at.hive13.org and solve the problem that way (there's already rewriting rules in the current Apache config to rewrite http to https).

**Comment by DrunkPyromaniac** [comment]
Made intweb.hive13.org redirect to intweb.at.hive13.org.
