### ISSUE TITLE
Ability to edit member email/paypal email

### ISSUE THREAD

**Issue by aeonsablaze** [Hive13/HiveWeb#8]
Having the ability to edit members emails (both paypal and regular) is going to be needed during the clean up of existing member data. In the long run this probably won't be necessary as new members should be entering it correctly, however if we are going to wait for existing members to correct the data we will be waiting a loooooong time.

**Comment by DrunkPyromaniac** [comment]
#13

**Comment by DrunkPyromaniac** [comment]
#19
